### ISSUE TITLE
test_ParallelNearestMeanClassifier fails with python 3.6

### ISSUE THREAD

**Issue by mwhudson** [mdp-toolkit/mdp-toolkit#26] opened 2017-07-14 00:12 UTC
Found when making Python 3.6 supported in Debian/Ubuntu (https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=867515).

This passes:

```
$ python3.5 -m pytest --seed=1029384756 mdp/test/test_parallelclassifiers.py  -k test_ParallelNearestMeanClassifier
```

This fails (consistently):

```
$ python3.6 -m pytest --seed=1029384756 mdp/test/test_parallelclassifiers.py  -k test_ParallelNearestMeanClassifier 
============================= test session starts ==============================
platform linux -- Python 3.6.2rc2, pytest-3.0.6, py-1.4.34, pluggy-0.4.0
          python: 3.6.2.candidate.2
             mdp: 3.5
 parallel python: NOT AVAILABLE: No module named 'pp'
          shogun: NOT AVAILABLE: No module named 'shogun'
          libsvm: NOT AVAILABLE: No module named 'svm'
          joblib: 0.10.4.dev0
         sklearn: 0.18
            numx: scipy 0.18.1
          symeig: scipy.linalg.eigh
Random Seed: 1029384756

rootdir: /mdp-3.5, inifile: pytest.ini
collected 3 items 

mdp/test/test_parallelclassifiers.py F

===================================== NOTE =====================================
          python: 3.6.2.candidate.2
             mdp: 3.5
 parallel python: NOT AVAILABLE: No module named 'pp'
          shogun: NOT AVAILABLE: No module named 'shogun'
          libsvm: NOT AVAILABLE: No module named 'svm'
          joblib: 0.10.4.dev0
         sklearn: 0.18
            numx: scipy 0.18.1
          symeig: scipy.linalg.eigh
Random Seed: 1029384756

IMPORTANT: some tests use random numbers. This could
occasionally lead to failures due to numerical degeneracies.
To rule this out, please run the tests more than once.
If you get reproducible failures please report a bug!

=================================== FAILURES ===================================
______________________ test_ParallelNearestMeanClassifier ______________________

    def test_ParallelNearestMeanClassifier():
        """Test ParallelGaussianClassifier."""
        precision = 6
        xs = [numx_rand.random([4,5]) for _ in range(8)]
        labels = [1,2,1,1,2,3,2,3]
        node = mdp.nodes.NearestMeanClassifier()
        pnode = parallel.ParallelNearestMeanClassifier()
        for i, x in enumerate(xs):
            node.train(x, labels[i])
        node.stop_training()
        pnode1 = pnode.fork()
        pnode2 = pnode.fork()
        for i, x in enumerate(xs):
            if i % 2:
                pnode1.train(x, labels[i])
            else:
                pnode2.train(x, labels[i])
        pnode.join(pnode1)
        pnode.join(pnode2)
        pnode.stop_training()
        # check that results are the same for all object classes
        assert_array_almost_equal(node.ordered_means, pnode.ordered_means,
>                                 precision)
E       AssertionError: 
E       Arrays are not almost equal to 6 decimals
E       
E       (mismatch 66.66666666666666%)
E        x: array([[ 0.399052,  0.586642,  0.446319,  0.522502,  0.474398],
E              [ 0.43769 ,  0.385436,  0.323763,  0.399375,  0.474671],
E              [ 0.569127,  0.311976,  0.673377,  0.653891,  0.391286]])
E        y: array([[ 0.43769 ,  0.385436,  0.323763,  0.399375,  0.474671],
E              [ 0.399052,  0.586642,  0.446319,  0.522502,  0.474398],
E              [ 0.569127,  0.311976,  0.673377,  0.653891,  0.391286]])

mdp/test/test_parallelclassifiers.py:58: AssertionError
============================== 2 tests deselected ==============================
==================== 1 failed, 2 deselected in 0.06 seconds ====================
```

**Comment by otizonaizit** [comment] 2017-07-15 09:26
Confirmed. Note that the failure is consistent also if you change the random seed, so something is wrong for real. 

@Debilski, @nwilbert : Looking at [What’s New In Python 3.6](https://docs.python.org/3/whatsnew/3.6.html) it seems to me that this bug is related to the changes in the dictionary object.

The array `ordered_means` has two rows flipped depeding on the Python version. The creation of the `self.ordered_means` array in `NearestMeanClassifier`  depends on the order of the keys in the dictionary `label_means`. That order has changed between Python 3.6 and Python 3.5. It is a miracle that it has worked without error until now (or was it a bug all along?)

@Debilski , @nwilbert : can you fix this? git blame tells me that @nwilbert was the last to modify the node. I think we need to branch out from tag MDP-3.5 to fix this, because master is broken in Python3 at the moment (one of the two recently merged PRs contained print statements). On a tangent note, we need to fix our travis CI so that we catch non python3 compatible code *before* merging ;-)

**Comment by nwilbert** [comment] 2017-07-16 19:38
Yes, the assertion in the test is wrong. I think we can simply delete the offending comparison, because this part of the object isn't affected by parallelization. Not that these tests are beautifull to begin with...

**Comment by mwhudson** [comment] 2017-07-16 23:19
Hi, thanks for the comments, I've cherry-picked that commit into Ubuntu for now.

**Comment by Stewori** [comment] 2018-06-15 10:44
Can this issue be closed?

**Comment by Stewori** [comment] 2019-02-21 20:35
Closing since this seems to be fixed and was inactive now for a while. Please reopen if necessary.

**Closed by Stewori** 2019-02-21 20:35 UTC
